Styles, mobile responsiveness, conditional tab rendering
holaplex/metaplex pull request #187
Opened 2021-12-29 07:44 UTC by sjc5

**Problems:**

- Many areas of the UI hide, overlap or are just generally hard to see / navigate on anything but a full desktop view of the storefront
- Listings nav tabs display even when no auctions fit the category (example, even if there are no secondary auctions, we are still rendering the "Secondary" tab
- Some copy and user action wording is confusing
- Over-use of ant design layout components at every layer of the DOM makes UI edits difficult / hacky

**This PR seeks to:**

- Generally improve UI and mobile responsiveness of most / all customer-facing views (artist-facing views still need work)
- Add slightly rounder corners and touch/press interactions to buttons for a more polished feel
- Make styling code / CSS a bit "friendlier" and more flexible for future updates
- Conditionally render auction listing nav tabs based on whether there are items to display

I know this is a monster PR, but given the broad scope of the task and the number of files that needed to be touched, there wasn't really a cleaner way to do this.

Probably 90% of the revisions are CSS/HTML only, and about 10% are React component refactors.

There are definitely more optimizations that are possible / desired (for example, properly scoping `.less` files and being completely consistent about where styling edits are applied across the entire application), but I think it makes sense to just submit this and discuss now before working any further.

Please let me know your comments. Thank you

2021-12-30 22:23 UTC, kespinola requested changes
Doing a great job but as you probably guessed I can not stand inline-styles. Please try and replace with a set of classname helpers like metaplex-spacing-top-lg. This is done to promote uniform spacing and styling.

2021-12-30 22:23 UTC, kespinola commented on js/packages/web/src/components/AuctionCard/index.tsx
> +              style={{ marginTop: '1rem', borderRadius: '5px' }}
Adjust border radius using ant theme variable so it applies to all buttons.

2021-12-30 22:23 UTC, kespinola commented on js/packages/web/src/components/ViewOn/styles.less
> +    text-decoration-color: #7777;
This should be based on theme variable.

2021-12-30 22:23 UTC, kespinola commented on js/packages/web/src/views/Listings/index.tsx
> +        }}
inline styles :(

2022-01-06 17:27 UTC, kristianeboe approved these changes
Let's do this :)

2022-01-06 18:50 UTC, kespinola approved these changes
Looks great. 🚀

2022-01-06 18:50 UTC, kespinola commented on js/packages/web/src/components/ArtContent/styles.less
> +    border-radius: @border-radius;
❤️

2022-01-06 18:50 UTC, kespinola commented on js/packages/web/src/components/AuctionRenderCard/index.tsx
> +            <p className="metaplex-margin-top-2 metaplex-margin-bottom-1 metaplex-reduced-font-size">
Nice. Loving what I'm seeing.

2022-01-06 18:50 UTC, kespinola commented on js/packages/web/src/components/Banner/index.tsx
> +        )} */}
Yeah lets delete the social since its not supported yet. We can reference these previous commits when we bring it back.

2022-01-06 18:50 UTC, kespinola commented on js/packages/web/src/views/Listings/index.tsx
> +                }
```suggestion
                className={cx("listings-menu-item-active": view === key)}
```

2022-01-06 18:50 UTC, kespinola commented on js/packages/web/src/views/art/index.tsx
Delete unused code.

2022-01-07 01:29 UTC, merged